// <auto-generated />
using System;
using CasualExplorer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasualExplorer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CasualExplorerDbContext))]
    [Migration("20240101000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ── CasualChain ───────────────────────────────────────────────────
            modelBuilder.Entity("CasualExplorer.Domain.Entities.CasualChain", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Domain").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("domain");
                b.Property<DateTime>("LastUpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("last_updated_at");
                b.Property<int>("NodeCount").HasColumnType("integer").HasColumnName("node_count");
                b.Property<Guid>("RootEventId").HasColumnType("uuid").HasColumnName("root_event_id");
                b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)").HasColumnName("title");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<int>("ViewCount").HasColumnType("integer").HasColumnName("view_count");
                b.HasKey("Id");
                b.HasIndex("Domain").HasDatabaseName("ix_causal_chains_domain");
                b.HasIndex("ViewCount").HasDatabaseName("ix_causal_chains_view_count");
                b.ToTable("causal_chains");
            });

            // ── CasualEdge ────────────────────────────────────────────────────
            modelBuilder.Entity("CasualExplorer.Domain.Entities.CasualEdge", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Explanation").IsRequired().HasMaxLength(2000).HasColumnType("character varying(2000)").HasColumnName("explanation");
                b.Property<Guid>("FromEventId").HasColumnType("uuid").HasColumnName("from_event_id");
                b.Property<bool>("IsContested").HasColumnType("boolean").HasColumnName("is_contested");
                b.Property<string>("Perspective").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("perspective");
                b.Property<string>("RelationshipType").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("relationship_type");
                b.Property<decimal>("Strength").HasPrecision(5, 4).HasColumnType("numeric(5,4)").HasColumnName("strength");
                b.Property<Guid>("ToEventId").HasColumnType("uuid").HasColumnName("to_event_id");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.HasKey("Id");
                b.HasIndex("FromEventId").HasDatabaseName("ix_causal_edges_from_event_id");
                b.HasIndex("ToEventId").HasDatabaseName("ix_causal_edges_to_event_id");
                b.HasIndex("FromEventId", "ToEventId").HasDatabaseName("ix_causal_edges_from_to");
                b.ToTable("causal_edges");

                b.OwnsMany("CasualExplorer.Domain.ValueObjects.Source", "Sources", b1 =>
                {
                    b1.Property<Guid>("CasualEdgeId").HasColumnType("uuid");
                    b1.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    b1.Property<string>("Url").IsRequired().HasMaxLength(2048).HasColumnName("url");
                    b1.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnName("title");
                    b1.Property<DateTime>("PublishedDate").HasColumnName("published_date");
                    b1.Property<decimal>("ReliabilityScore").HasPrecision(5, 4).HasColumnName("reliability_score");
                    b1.Property<string>("SourceType").HasMaxLength(50).HasColumnName("source_type");
                    b1.ToJson("sources");
                    b1.WithOwner().HasForeignKey("CasualEdgeId");
                    b1.HasKey("CasualEdgeId", "Id");
                });
            });

            // ── EventNode ─────────────────────────────────────────────────────
            modelBuilder.Entity("CasualExplorer.Domain.Entities.EventNode", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<decimal>("ConfidenceScore").HasPrecision(5, 4).HasColumnType("numeric(5,4)").HasColumnName("confidence_score");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Domain").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("domain");
                b.Property<DateTime>("EventDate").HasColumnType("timestamp with time zone").HasColumnName("event_date");
                b.Property<decimal>("FreshnessScore").HasPrecision(5, 4).HasColumnType("numeric(5,4)").HasColumnName("freshness_score");
                b.Property<bool>("IsVerified").HasColumnType("boolean").HasColumnName("is_verified");
                b.Property<string>("Summary").IsRequired().HasMaxLength(5000).HasColumnType("character varying(5000)").HasColumnName("summary");
                b.Property<string>("Title").IsRequired().HasMaxLength(300).HasColumnType("character varying(300)").HasColumnName("title");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");

                // _perspectives backing field
                b.Property<System.Collections.Generic.List<CasualExplorer.Domain.Enums.Perspective>>("_perspectives")
                    .HasMaxLength(500).HasColumnType("character varying(500)").HasColumnName("perspectives")
                    .UsePropertyAccessMode(Microsoft.EntityFrameworkCore.PropertyAccessMode.Field);

                b.HasKey("Id");
                b.HasIndex("Domain").HasDatabaseName("ix_event_nodes_domain");
                b.HasIndex("EventDate").HasDatabaseName("ix_event_nodes_event_date");
                b.HasIndex("IsVerified").HasDatabaseName("ix_event_nodes_is_verified");
                b.ToTable("event_nodes");

                b.OwnsMany("CasualExplorer.Domain.ValueObjects.Source", "Sources", b1 =>
                {
                    b1.Property<Guid>("EventNodeId").HasColumnType("uuid");
                    b1.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    b1.Property<string>("Url").IsRequired().HasMaxLength(2048).HasColumnName("url");
                    b1.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnName("title");
                    b1.Property<DateTime>("PublishedDate").HasColumnName("published_date");
                    b1.Property<decimal>("ReliabilityScore").HasPrecision(5, 4).HasColumnName("reliability_score");
                    b1.Property<string>("SourceType").HasMaxLength(50).HasColumnName("source_type");
                    b1.ToJson("sources");
                    b1.WithOwner().HasForeignKey("EventNodeId");
                    b1.HasKey("EventNodeId", "Id");
                });
            });

            // ── RefreshTokenRecord ────────────────────────────────────────────
            modelBuilder.Entity("CasualExplorer.Infrastructure.Persistence.RefreshTokenRecord", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("character varying(45)").HasColumnName("created_by_ip");
                b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                b.Property<bool>("IsRevoked").HasColumnType("boolean").HasColumnName("is_revoked");
                b.Property<string>("Token").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)").HasColumnName("token");
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.HasKey("Id");
                b.HasIndex("Token").IsUnique().HasDatabaseName("uq_refresh_tokens_token");
                b.HasIndex("UserId").HasDatabaseName("ix_refresh_tokens_user_id");
                b.ToTable("refresh_tokens");
            });

            // ── User ──────────────────────────────────────────────────────────
            modelBuilder.Entity("CasualExplorer.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("character varying(320)").HasColumnName("email");
                b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                b.Property<DateTime?>("LastLoginAt").HasColumnType("timestamp with time zone").HasColumnName("last_login_at");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("password_hash");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)").HasColumnName("role");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("username");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique().HasDatabaseName("uq_users_email");
                b.HasIndex("Username").IsUnique().HasDatabaseName("uq_users_username");
                b.ToTable("users");
            });

            // ── UserSavedChain ────────────────────────────────────────────────
            modelBuilder.Entity("CasualExplorer.Domain.Entities.UserSavedChain", b =>
            {
                b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                b.Property<Guid>("ChainId").HasColumnType("uuid").HasColumnName("chain_id");
                b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("character varying(1000)").HasColumnName("notes");
                b.Property<DateTime>("SavedAt").HasColumnType("timestamp with time zone").HasColumnName("saved_at");
                b.HasKey("UserId", "ChainId");
                b.HasIndex("ChainId").HasDatabaseName("IX_user_saved_chains_chain_id");
                b.ToTable("user_saved_chains");
            });

            // ── Relationships ─────────────────────────────────────────────────
            modelBuilder.Entity("CasualExplorer.Domain.Entities.CasualEdge", b =>
            {
                b.HasOne("CasualExplorer.Domain.Entities.EventNode", null)
                    .WithMany()
                    .HasForeignKey("FromEventId")
                    .HasConstraintName("FK_causal_edges_event_nodes_from_event_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CasualExplorer.Domain.Entities.EventNode", null)
                    .WithMany()
                    .HasForeignKey("ToEventId")
                    .HasConstraintName("FK_causal_edges_event_nodes_to_event_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CasualExplorer.Infrastructure.Persistence.RefreshTokenRecord", b =>
            {
                b.HasOne("CasualExplorer.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .HasConstraintName("FK_refresh_tokens_users_user_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("CasualExplorer.Domain.Entities.UserSavedChain", b =>
            {
                b.HasOne("CasualExplorer.Domain.Entities.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .HasConstraintName("FK_user_saved_chains_users_user_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("CasualExplorer.Domain.Entities.CasualChain", null)
                    .WithMany()
                    .HasForeignKey("ChainId")
                    .HasConstraintName("FK_user_saved_chains_causal_chains_chain_id")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
