namespace CasualExplorer.Application.Common.DTOs;

/// <summary>
/// Represents a casual event node generated by the AI knowledge-graph pipeline.
/// </summary>
/// <param name="Id">Stable UUID string assigned by the AI service.</param>
/// <param name="Title">Short descriptive title of the event.</param>
/// <param name="Summary">Multi-sentence summary of what happened and why it matters.</param>
/// <param name="EventDate">ISO 8601 date of the event (e.g. "2023-06-01").</param>
/// <param name="Domain">Domain name string (e.g. "Geopolitics", "Economics").</param>
/// <param name="ConfidenceScore">AI-assigned confidence score in [0, 1].</param>
/// <param name="FreshnessScore">Freshness score in [0, 1].</param>
/// <param name="SourceUrl">URL of the Wikipedia article this event was sourced from.</param>
/// <param name="SourceTitle">Display title of the source article.</param>
public sealed record GeneratedEventDto(
    string Id,
    string Title,
    string Summary,
    string EventDate,
    string Domain,
    double ConfidenceScore,
    double FreshnessScore,
    string SourceUrl,
    string SourceTitle);

/// <summary>
/// Represents a directed casual edge generated by the AI knowledge-graph pipeline.
/// </summary>
/// <param name="FromEventId">UUID string of the cause event node.</param>
/// <param name="ToEventId">UUID string of the effect event node.</param>
/// <param name="RelationshipType">Relationship type string (e.g. "DirectlyCaused", "ContributedTo").</param>
/// <param name="Strength">Strength of the casual link in [0, 1].</param>
/// <param name="Perspective">Analytical perspective string (e.g. "Mainstream", "Geopolitical").</param>
/// <param name="Explanation">Human-readable explanation of the casual mechanism.</param>
/// <param name="IsContested">Whether the relationship is actively contested.</param>
public sealed record GeneratedEdgeDto(
    string FromEventId,
    string ToEventId,
    string RelationshipType,
    double Strength,
    string Perspective,
    string Explanation,
    bool IsContested);

/// <summary>
/// The full graph payload returned by <see cref="Interfaces.IKnowledgeGraphGenerator"/>.
/// </summary>
/// <param name="Topic">The original topic used to generate this graph.</param>
/// <param name="Events">Extracted event nodes.</param>
/// <param name="Edges">Inferred casual edges between the extracted events.</param>
/// <param name="SourceUrls">Wikipedia URLs used as source material.</param>
/// <param name="FromCache">Whether this result was served from the in-memory cache.</param>
public sealed record GeneratedGraphDto(
    string Topic,
    IReadOnlyList<GeneratedEventDto> Events,
    IReadOnlyList<GeneratedEdgeDto> Edges,
    IReadOnlyList<string> SourceUrls,
    bool FromCache);
