"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { useBreakpoint } from "@/hooks/useBreakpoint";

const requestLines = [
  { t: "comment", text: "# Causal graph search — semantic fallback + Grok generation" },
  { t: "blank" },
  { t: "method",  method: "GET", path: " /api/v1/EventNodes/search" },
  { t: "blank" },
  { t: "param",   key: "  ?q",     val: "=why is rupee falling against usd" },
  { t: "param",   key: "  &mode",  val: "=balanced" },
  { t: "param",   key: "  &count", val: "=10" },
  { t: "blank" },
  { t: "header",  key: "Accept",        val: "application/json" },
  { t: "header",  key: "Authorization", val: "Bearer <token>" },
];

const responseLines = [
  '{',
  '  "items": [',
  '    {',
  '      "id": "3f8a2c1d-...",',
  '      "title": "US Federal Reserve hikes rates",',
  '      "domain": "Economics",',
  '      "confidenceScore": 0.91,',
  '      "eventDate": "2022-03-16"',
  '    },',
  '    {',
  '      "id": "7b3e9f2a-...",',
  '      "title": "Capital Flight from Emerging Markets",',
  '      "confidenceScore": 0.84',
  '    }',
  '    // ... 8 more nodes',
  '  ],',
  '  "totalCount": 10,',
  '  "wasAutoGenerated": true,',
  '  "cacheHit": false',
  '}',
];

const stats = [
  { value: "3",      label: "Search phases" },
  { value: "0.70",   label: "Semantic threshold" },
  { value: "<100ms", label: "Cache latency" },
  { value: "36/36",  label: "Tests passing" },
];

function TitleBar({ label }: { label: string }) {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 7, padding: "9px 16px", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
      {["rgba(255,80,80,0.55)","rgba(255,200,50,0.55)","rgba(50,205,100,0.55)"].map((c, i) => (
        <span key={i} style={{ width: 8, height: 8, borderRadius: "50%", background: c, display: "inline-block" }} />
      ))}
      <span style={{ fontSize: 10, color: "rgba(255,255,255,0.2)", fontFamily: "monospace", marginLeft: 4 }}>{label}</span>
    </div>
  );
}

function RequestPane({ compact }: { compact?: boolean }) {
  return (
    <div>
      <TitleBar label="Request" />
      <div style={{ padding: compact ? "16px 16px" : "20px 24px", fontFamily: "monospace", fontSize: compact ? 11 : 12.5, lineHeight: 1.75 }}>
        {requestLines.map((line, i) => {
          if (line.t === "blank")   return <div key={i} style={{ height: 6 }} />;
          if (line.t === "comment") return <div key={i} style={{ color: "rgba(255,255,255,0.18)" }}>{line.text}</div>;
          if (line.t === "method")  return (
            <div key={i}><span style={{ color: "#4ade80", fontWeight: 700 }}>{line.method}</span><span style={{ color: "rgba(255,255,255,0.6)" }}>{line.path}</span></div>
          );
          if (line.t === "param")   return (
            <div key={i}><span style={{ color: "#38bdf8" }}>{line.key}</span><span style={{ color: "#fbbf24" }}>{line.val}</span></div>
          );
          if (line.t === "header")  return (
            <div key={i}><span style={{ color: "#c084fc" }}>{line.key}</span><span style={{ color: "rgba(255,255,255,0.22)" }}>: </span><span style={{ color: "rgba(255,255,255,0.4)" }}>{line.val}</span></div>
          );
          return null;
        })}
        <div style={{ marginTop: 14, display: "flex", alignItems: "center", gap: 7 }}>
          <span style={{ width: 6, height: 6, borderRadius: "50%", background: "#4ade80", display: "inline-block" }} />
          <span style={{ fontSize: 10, color: "rgba(255,255,255,0.26)", fontFamily: "monospace" }}>200 OK · 44ms · 8.2 kB</span>
        </div>
      </div>
    </div>
  );
}

function ResponsePane({ compact }: { compact?: boolean }) {
  return (
    <div>
      <TitleBar label="Response" />
      <div style={{ padding: compact ? "16px 16px" : "20px 24px", fontFamily: "monospace", fontSize: compact ? 11 : 12, lineHeight: 1.75 }}>
        {responseLines.map((line, i) => {
          const keyMatch = line.match(/^(\s*)("[\w]+")(\s*:\s*)(.*)/);
          if (keyMatch) {
            const [, , key, colon, val] = keyMatch;
            const isStr  = val.startsWith('"');
            const isNum  = /^[0-9.\-]/.test(val.trim());
            const isBool = val.trim() === "true" || val.trim() === "false";
            return (
              <div key={i}>
                <span style={{ color: "#38bdf8" }}>{key}</span>
                <span style={{ color: "rgba(255,255,255,0.22)" }}>{colon}</span>
                <span style={{ color: isStr ? "#fbbf24" : isNum ? "#4ade80" : isBool ? "#c084fc" : "rgba(255,255,255,0.5)" }}>{val}</span>
              </div>
            );
          }
          if (line.trim().startsWith("//")) return <div key={i} style={{ color: "rgba(255,255,255,0.18)" }}>{line}</div>;
          return <div key={i} style={{ color: "rgba(255,255,255,0.3)" }}>{line}</div>;
        })}
      </div>
    </div>
  );
}

export default function ApiPreview() {
  const [copied, setCopied] = useState(false);
  const bp = useBreakpoint();
  const isMobile = bp === "mobile";
  const isTablet = bp === "tablet";
  const isNarrow = isMobile || isTablet;

  const px = isMobile ? "20px" : isTablet ? "28px" : "40px";
  const statCols = isMobile ? 2 : 4;

  function copyEndpoint() {
    navigator.clipboard.writeText("GET /api/v1/EventNodes/search?q=why+is+rupee+falling&mode=balanced&count=10");
    setCopied(true);
    setTimeout(() => setCopied(false), 1800);
  }

  return (
    <div style={{ flex: 1, display: "flex", flexDirection: "column", minHeight: 0, background: "#14100e", overflow: "hidden" }}>
      <div className="mw" style={{ width: "100%", flex: 1, display: "flex", flexDirection: "column", minHeight: 0 }}>
      {/* Header */}
      <div
        style={{
          padding: isMobile ? "20px 20px 16px" : `24px ${px} 20px`,
          borderBottom: "1px solid rgba(255,255,255,0.06)",
          display: "flex",
          flexDirection: isMobile ? "column" : "row",
          alignItems: isMobile ? "flex-start" : "baseline",
          justifyContent: "space-between",
          gap: isMobile ? 8 : 24,
        }}
      >
        <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.12em", color: "rgba(255,255,255,0.25)", textTransform: "uppercase", flexShrink: 0 }}>
          API Preview
        </span>
        <h2 style={{ fontSize: isMobile ? "clamp(20px,6vw,28px)" : "clamp(24px, 3vw, 38px)", fontWeight: 800, letterSpacing: "-0.03em", color: "#fff", lineHeight: 1 }}>
          One endpoint. Full causal graph.
        </h2>
      </div>

      {/* Terminal split — side-by-side on desktop, stacked on mobile */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: isNarrow ? "1fr" : "1fr 1fr",
          borderBottom: "1px solid rgba(255,255,255,0.06)",
          flex: 1,
          minHeight: 0,
        }}
      >
        <div style={{ borderRight: isNarrow ? "none" : "1px solid rgba(255,255,255,0.06)", borderBottom: isNarrow ? "1px solid rgba(255,255,255,0.06)" : "none" }}>
          <RequestPane compact={isMobile} />
        </div>
        <div>
          <ResponsePane compact={isMobile} />
        </div>
      </div>

      {/* Copy endpoint */}
      <div
        style={{
          padding: isMobile ? "14px 20px" : "16px 40px",
          borderBottom: "1px solid rgba(255,255,255,0.06)",
          display: "flex",
          alignItems: "center",
          gap: 12,
          flexWrap: "wrap",
        }}
      >
        <code style={{ fontSize: isMobile ? 10 : 12, fontFamily: "monospace", color: "rgba(255,255,255,0.3)", flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
          GET /api/v1/EventNodes/search?q=...&amp;mode=balanced&amp;count=10
        </code>
        <motion.button
          whileTap={{ scale: 0.95 }}
          onClick={copyEndpoint}
          style={{
            background: "transparent",
            border: "1px solid rgba(255,255,255,0.14)",
            color: copied ? "#4ade80" : "rgba(255,255,255,0.4)",
            fontSize: 10,
            fontWeight: 700,
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            padding: "5px 12px",
            cursor: "pointer",
            fontFamily: "inherit",
            flexShrink: 0,
            transition: "color 0.15s",
          }}
        >
          {copied ? "Copied!" : "Copy"}
        </motion.button>
      </div>

      {/* Stats strip */}
      <div style={{ display: "grid", gridTemplateColumns: `repeat(${statCols}, 1fr)` }}>
        {stats.map((s, i) => (
          <motion.div
            key={s.label}
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0 }}
            transition={{ delay: i * 0.08, duration: 0.4 }}
            style={{
              padding: isMobile ? "20px 16px" : "26px 36px",
              borderRight: (i + 1) % statCols !== 0 ? "1px solid rgba(255,255,255,0.05)" : "none",
              borderBottom: isMobile && i < 2 ? "1px solid rgba(255,255,255,0.05)" : "none",
            }}
          >
            <div style={{ fontSize: isMobile ? 24 : 30, fontWeight: 900, color: "#fff", letterSpacing: "-0.04em", lineHeight: 1 }}>{s.value}</div>
            <div style={{ fontSize: 9, color: "rgba(255,255,255,0.28)", marginTop: 6, letterSpacing: "0.06em", textTransform: "uppercase" }}>{s.label}</div>
          </motion.div>
        ))}
      </div>
      </div>{/* close .mw wrapper */}
    </div>
  );
}
