// ─── Demo Preview ─────────────────────────────────────────────────────────────

const requestLines = [
  { type: "comment", text: "# Search with semantic fallback + Grok generation" },
  { type: "method", text: "GET ", rest: "/api/v1/EventNodes/search" },
  { type: "blank", text: "" },
  { type: "param", key: "  ?q", value: "=why is rupee falling against usd" },
  { type: "param", key: "  &mode", value: "=balanced" },
  { type: "param", key: "  &count", value: "=10" },
  { type: "blank", text: "" },
  { type: "header", key: "Accept", value: "application/json" },
  { type: "header", key: "Authorization", value: "Bearer <token>" },
];

const responseJson = `{
  "items": [
    {
      "id": "3f8a2c1d-...",
      "title": "US Federal Reserve hikes interest rates",
      "summary": "The Fed raised rates to combat inflation, strengthening the USD and making emerging market currencies like the INR weaker.",
      "eventDate": "2022-03-16",
      "domain": "Economics",
      "confidenceScore": 0.91,
      "sourceUrl": "https://en.wikipedia.org/wiki/Federal_funds_rate"
    },
    {
      "id": "7b3e9f2a-...",
      "title": "Capital Flight from Emerging Markets",
      "summary": "Higher US yields triggered large-scale withdrawal of foreign portfolio investments from India, putting downward pressure on the rupee.",
      "eventDate": "2022-06-10",
      "domain": "Economics",
      "confidenceScore": 0.84,
      "sourceUrl": "https://en.wikipedia.org/wiki/Capital_flight"
    },
    {
      "id": "1c5d8e4b-...",
      "title": "India's Trade Deficit Widens",
      "summary": "Rising crude oil prices — denominated in USD — pushed India's import bill higher, deepening the current account deficit.",
      "eventDate": "2022-08-22",
      "domain": "Economics",
      "confidenceScore": 0.87,
      "sourceUrl": "https://en.wikipedia.org/wiki/India–United_States_relations"
    }
    // ... 7 more nodes
  ],
  "totalCount": 10,
  "wasAutoGenerated": true,
  "generatedFromSources": [
    "https://en.wikipedia.org/wiki/Indian_rupee",
    "https://en.wikipedia.org/wiki/Federal_funds_rate"
  ]
}`;

export default function DemoPreview() {
  return (
    <section id="demo" className="bg-[#e8e8e8] py-6 px-6">
      <div className="mx-auto" style={{ maxWidth: 1100 }}>
        {/* Header */}
        <div className="bg-white rounded-3xl p-10 mb-4 shadow-sm">
          <div className="inline-flex items-center gap-2 border border-gray-200 rounded-full px-3 py-1 mb-5">
            <span className="w-2 h-2 bg-black rounded-none inline-block" />
            <span className="text-[11px] font-semibold tracking-widest text-black uppercase">
              API Preview
            </span>
          </div>
          <div className="flex items-end justify-between">
            <h2
              className="text-[42px] font-black leading-none tracking-tight text-black"
              style={{ fontFamily: "'Arial Black', sans-serif" }}
            >
              One endpoint.
              <br />
              Full causal graph.
            </h2>
            <p className="text-[13.5px] text-gray-400 max-w-[280px] text-right leading-relaxed">
              A single GET request returns a paginated graph — auto-generated
              by Grok if nothing exists, cached in Redis on repeat.
            </p>
          </div>
        </div>

        {/* Terminal split */}
        <div className="grid grid-cols-2 gap-4">
          {/* Request pane */}
          <div className="bg-[#111] rounded-3xl overflow-hidden shadow-sm">
            {/* Title bar */}
            <div className="flex items-center gap-2 px-5 py-4 border-b border-white/5">
              <span className="w-3 h-3 rounded-full bg-red-500/70" />
              <span className="w-3 h-3 rounded-full bg-yellow-500/70" />
              <span className="w-3 h-3 rounded-full bg-green-500/70" />
              <span className="ml-3 text-[11px] text-white/30 font-mono">
                Request
              </span>
            </div>
            <div className="p-6 font-mono text-[12.5px] leading-relaxed">
              {requestLines.map((line, i) => {
                if (line.type === "blank") return <div key={i} className="h-3" />;
                if (line.type === "comment")
                  return (
                    <div key={i} className="text-white/25 mb-1">
                      {line.text}
                    </div>
                  );
                if (line.type === "method")
                  return (
                    <div key={i} className="mb-1">
                      <span className="text-emerald-400">{line.text}</span>
                      <span className="text-white/70">{line.rest}</span>
                    </div>
                  );
                if (line.type === "param")
                  return (
                    <div key={i} className="mb-0.5">
                      <span className="text-sky-400">{line.key}</span>
                      <span className="text-amber-300">{line.value}</span>
                    </div>
                  );
                if (line.type === "header")
                  return (
                    <div key={i} className="mb-0.5">
                      <span className="text-purple-400">{line.key}</span>
                      <span className="text-white/40">: </span>
                      <span className="text-white/60">{line.value}</span>
                    </div>
                  );
                return null;
              })}

              {/* Timing badge */}
              <div className="mt-6 flex items-center gap-2">
                <span className="w-1.5 h-1.5 bg-emerald-400 rounded-full" />
                <span className="text-[11px] text-white/40">
                  200 OK · 44ms (cache hit) · 8.2 kB
                </span>
              </div>
            </div>
          </div>

          {/* Response pane */}
          <div className="bg-[#111] rounded-3xl overflow-hidden shadow-sm">
            {/* Title bar */}
            <div className="flex items-center gap-2 px-5 py-4 border-b border-white/5">
              <span className="w-3 h-3 rounded-full bg-red-500/70" />
              <span className="w-3 h-3 rounded-full bg-yellow-500/70" />
              <span className="w-3 h-3 rounded-full bg-green-500/70" />
              <span className="ml-3 text-[11px] text-white/30 font-mono">
                Response
              </span>
            </div>
            <div className="p-6 overflow-auto" style={{ maxHeight: 380 }}>
              <pre className="font-mono text-[11.5px] leading-relaxed whitespace-pre-wrap">
                {responseJson.split("\n").map((line, i) => {
                  // key strings
                  const keyMatch = line.match(/^(\s*)("[\w]+")(\s*:\s*)(.*)/);
                  if (keyMatch) {
                    const [, indent, key, colon, val] = keyMatch;
                    const isString = val.startsWith('"') || val.startsWith("'");
                    const isNumber = /^[0-9.\-]/.test(val.trim());
                    const isBool = val.trim() === "true" || val.trim() === "false";
                    return (
                      <div key={i}>
                        <span className="text-white/30">{indent}</span>
                        <span className="text-sky-400">{key}</span>
                        <span className="text-white/30">{colon}</span>
                        <span className={
                          isString ? "text-amber-300" :
                          isNumber ? "text-emerald-400" :
                          isBool ? "text-purple-400" :
                          "text-white/60"
                        }>{val}</span>
                      </div>
                    );
                  }
                  // comment / ellipsis lines
                  if (line.trim().startsWith("//"))
                    return <div key={i} className="text-white/25">{line}</div>;
                  return <div key={i} className="text-white/40">{line}</div>;
                })}
              </pre>
            </div>
          </div>
        </div>

        {/* Stats strip */}
        <div className="bg-white rounded-3xl mt-4 px-10 py-6 shadow-sm grid grid-cols-4 divide-x divide-gray-100">
          {[
            { value: "3", label: "Search phases" },
            { value: "0.70", label: "Semantic threshold" },
            { value: "<100ms", label: "Cache hit latency" },
            { value: "20", label: "Max event nodes" },
          ].map((stat) => (
            <div key={stat.label} className="px-8 first:pl-0 last:pr-0">
              <p className="text-[32px] font-black text-black tracking-tight leading-none">
                {stat.value}
              </p>
              <p className="text-[12px] text-gray-400 mt-1.5">{stat.label}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
