namespace CausalExplorer.Application.Common.Models;

/// <summary>
/// Wraps a paged subset of query results along with pagination metadata.
/// </summary>
/// <typeparam name="T">The item type in the page.</typeparam>
public sealed class PagedResult<T>
{
    /// <summary>Gets the items in the current page.</summary>
    public IReadOnlyList<T> Items { get; }

    /// <summary>Gets the total number of items across all pages.</summary>
    public int TotalCount { get; }

    /// <summary>Gets the current 1-based page number.</summary>
    public int Page { get; }

    /// <summary>Gets the maximum number of items per page.</summary>
    public int PageSize { get; }

    /// <summary>Gets the total number of pages.</summary>
    public int TotalPages => (int)Math.Ceiling(TotalCount / (double)PageSize);

    /// <summary>Gets a value indicating whether there is a previous page.</summary>
    public bool HasPreviousPage => Page > 1;

    /// <summary>Gets a value indicating whether there is a next page.</summary>
    public bool HasNextPage => Page < TotalPages;

    /// <summary>
    /// Gets a value indicating whether these results were automatically generated
    /// from Wikipedia + LLM because no sufficiently relevant existing data was found.
    /// </summary>
    public bool WasAutoGenerated { get; init; }

    /// <summary>
    /// Gets the Wikipedia URLs used as source material when <see cref="WasAutoGenerated"/> is <c>true</c>.
    /// Empty for normal search results.
    /// </summary>
    public IReadOnlyList<string> GeneratedFromSources { get; init; } = [];

    /// <summary>
    /// Initialises a new <see cref="PagedResult{T}"/>.
    /// </summary>
    public PagedResult(IReadOnlyList<T> items, int totalCount, int page, int pageSize)
    {
        Items      = items;
        TotalCount = totalCount;
        Page       = page;
        PageSize   = pageSize;
    }

    /// <summary>Creates an empty result for the given pagination parameters.</summary>
    public static PagedResult<T> Empty(int page, int pageSize) =>
        new([], 0, page, pageSize);
}
